import Colors from "@/utils/Colors";
import Dimenstion from "@/utils/Dimenstion";
import { Dimensions, StyleSheet } from "react-native";
const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#fff' },
    loader: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    header: {
        marginBottom: 24,
        backgroundColor: Colors.PRIMARY,
        paddingVertical: 20,
        paddingHorizontal: 16,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        height: Dimenstion.headerHeight,
    },
    headerTitle: { color: Colors.WHITE, fontSize: 20, fontWeight: 'bold' },

    section: { paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1, borderColor: '#eee' },
    sectionTitle: { fontSize: 18, fontWeight: '600', marginBottom: 12 },

    itemRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
    itemImg: { width: 60, height: 60, borderRadius: 6, marginRight: 12 },
    qtyTxt: { fontSize: 12, color: '#666' },
    priceTxt: { fontSize: 14, fontWeight: '600' },

    // Payment Method Section
    paymentMethodSection: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    paymentMethodOption: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        padding: 12,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 8,
        marginBottom: 8,
    },
    selectedPaymentMethod: {
        borderColor: Colors.PRIMARY,
        backgroundColor: '#f0f8ff',
    },
    disabledPaymentMethod: {
        borderColor: '#ddd',
        backgroundColor: '#f9f9f9',
        opacity: 0.6,
    },
    paymentMethodRadio: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#ccc',
        marginRight: 12,
        marginTop: 2,
        justifyContent: 'center',
        alignItems: 'center',
    },
    paymentMethodRadioSelected: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: Colors.PRIMARY,
    },
    paymentMethodInfo: { flex: 1 },
    paymentMethodHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    paymentMethodTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: Colors.PRIMARY,
        marginLeft: 8,
    },
    paymentMethodDescription: {
        fontSize: 14,
        color: '#666',
        marginBottom: 8,
    },
    disabledText: {
        color: '#999',
    },
    codBadge: {
        alignSelf: 'flex-start',
        backgroundColor: '#00a650',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    codBadgeText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
    paymentRestrictionInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 12,
        padding: 12,
        backgroundColor: '#fff8e1',
        borderRadius: 8,
    },
    paymentRestrictionText: {
        fontSize: 12,
        color: '#666',
        marginLeft: 8,
        flex: 1,
    },
    paymentSummary: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 8,
        paddingTop: 8,
        borderTopWidth: 1,
        borderTopColor: '#eee',
    },
    paymentSummaryLabel: { fontSize: 14, color: '#666' },
    paymentSummaryValue: { fontSize: 14, fontWeight: '500', color: Colors.PRIMARY },

    // Summary styles
    summaryRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 },
    discountValue: { color: '#00a650' },
    totalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#eee',
    },
    totalLabel: { fontSize: 18, fontWeight: 'bold' },
    totalValue: { fontSize: 20, fontWeight: 'bold', color: Colors.PRIMARY },

    tabsRow: { flexDirection: 'row', marginBottom: 12 },
    tabBtn: { flex: 1, paddingVertical: 8, alignItems: 'center', borderBottomWidth: 2, borderColor: 'transparent' },
    tabBtnActive: { borderColor: Colors.PRIMARY },
    tabTxt: { color: '#666', fontSize: 14 },
    tabTxtActive: { color: Colors.PRIMARY, fontWeight: '600' },

    checkboxRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    checkboxLabel: { marginLeft: 8, fontSize: 14, color: '#333' },

    editBtn: { alignSelf: 'flex-end', marginBottom: 8 },
    editTxt: { color: Colors.PRIMARY, fontWeight: '600' },
    input: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 6,
        padding: 10,
        marginBottom: 4,
        fontSize: 14,
    },
    inputError: {
        borderColor: '#ff4444',
        borderWidth: 1.5,
    },
    errorText: {
        color: '#ff4444',
        fontSize: 12,
        marginBottom: 8,
        marginLeft: 4,
    },
    addrLine: { color: '#333', lineHeight: 22 },
    saveBtn: { backgroundColor: Colors.PRIMARY, padding: 12, borderRadius: 6, alignItems: 'center', marginTop: 8 },
    saveTxt: { color: Colors.WHITE, fontWeight: 'bold' },

    // Additional styles from Cart
    loadingSection: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
    },
    loadingText: {
        marginLeft: 8,
        fontSize: 14,
        color: '#666',
    },
    infoSection: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        alignItems: 'center',
    },
    infoText: {
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
    },
    freeShippingText: {
        fontSize: 12,
        color: '#00a650',
        marginTop: 4,
    },
    shippingMethodsSection: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    shippingMethodOption: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 8,
        marginBottom: 8,
    },
    selectedShippingMethod: {
        borderColor: Colors.PRIMARY,
        backgroundColor: '#f0f8ff',
    },
    shippingMethodRadio: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#ccc',
        marginRight: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    shippingMethodRadioSelected: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: Colors.PRIMARY,
    },
    shippingMethodInfo: { flex: 1 },
    shippingMethodTitle: { fontSize: 16, fontWeight: '600', marginBottom: 4 },
    shippingMethodDescription: { fontSize: 12, color: '#666' },
    shippingMethodCost: { fontSize: 16, fontWeight: 'bold', color: Colors.PRIMARY },
    selectedShippingInfo: {
        marginTop: 12,
        padding: 12,
        backgroundColor: '#f0f8ff',
        borderRadius: 8,
        alignItems: 'center',
    },
    selectedShippingText: {
        fontSize: 14,
        fontWeight: '500',
        color: Colors.PRIMARY,
    },
    couponSection: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    
    // couponItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
    couponIcon: { marginRight: 8 },
    couponCode: { fontSize: 14, fontWeight: '500', flex: 1 },
    couponDiscount: { fontSize: 14, color: '#00a650', fontWeight: 'bold' },
    taxSection: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    noTaxItem: {
        paddingVertical: 12,
        alignItems: 'center',
    },
    noTaxText: {
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
    },
    taxItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
    taxIcon: { marginRight: 8 },
    taxLabel: { fontSize: 13, color: '#666', flex: 1 },
    taxAmount: { fontSize: 13, fontWeight: '500' },
    gstBreakdownHeader: {
        borderTopWidth: 1,
        borderTopColor: '#e0e0e0',
        marginTop: 8,
        paddingTop: 8,
        marginBottom: 6,
    },
    gstBreakdownTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: Colors.PRIMARY,
    },
    totalTaxRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 6,
        paddingTop: 6,
        borderTopWidth: 1,
        borderTopColor: '#e0e0e0',
    },
    totalTaxLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
    },
    totalTaxAmount: {
        fontSize: 14,
        fontWeight: '600',
        color: Colors.PRIMARY,
    },

    bottomContainer: {
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#eee',
        paddingHorizontal: 16,
        paddingTop: 16,
    },
    placeBtn: {
        backgroundColor: Colors.PRIMARY,
        padding: 16,
        alignItems: 'center',
        borderRadius: 8,
    },
    placeTxt: { color: Colors.WHITE, fontSize: 16, fontWeight: 'bold' },

    toast: {
        position: 'absolute',
        left: 20,
        right: 20,
        backgroundColor: '#333',
        padding: 14,
        borderRadius: 8,
        alignItems: 'center'
    },
    toastTxt: { color: '#fff' },
    couponItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#F0F9FF',
        padding: 12,
        borderRadius: 8,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#BAE6FD',
    },
    couponInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    removeCouponButton: {
        padding: 4,
        marginLeft: 8,
    },
});

export default styles;

